/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jplay.test;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author pperezp
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jSlider1.setVisible(jToggleButton1.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jplay/recursos/iconos/1443343087_volume-up.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl2.setText("jLabel3");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 2, 130, 130));

        lbl1.setText("jLabel2");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 130, 130));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton1)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        jSlider1.setVisible(jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        jToggleButton1.setSelected(false);
        jSlider1.setVisible(jToggleButton1.isSelected());
    }//GEN-LAST:event_jSlider1MouseReleased

    private void cLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cLabel1MouseExited
//        cLabel1.setBackground(new java.awt.Color(233, 30, 99));
    }//GEN-LAST:event_cLabel1MouseExited

    private void cLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cLabel1MouseEntered
//        cLabel1.setBackground(new java.awt.Color(236, 64, 122));
    }//GEN-LAST:event_cLabel1MouseEntered

    private void cLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cLabel1MousePressed
//        cLabel1.setBackground(new java.awt.Color(194, 24, 91));
    }//GEN-LAST:event_cLabel1MousePressed

    private void cLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cLabel1MouseReleased
//        cLabel1.setBackground(new java.awt.Color(233, 30, 99));
    }//GEN-LAST:event_cLabel1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Image im1 = new ImageIcon("test/01.jpg").getImage();
        Image im2 = new ImageIcon("test/02.jpg").getImage();
        Image im3 = new ImageIcon("test/03.jpg").getImage();
        Image im4 = new ImageIcon("test/04.jpg").getImage();
        Image im5 = new ImageIcon("test/05.png").getImage();

        ImageIcon ii1 = new ImageIcon(im1.getScaledInstance(130, 130, Image.SCALE_SMOOTH));
        ImageIcon ii2 = new ImageIcon(im2.getScaledInstance(130, 130, Image.SCALE_SMOOTH));
        ImageIcon ii3 = new ImageIcon(im3.getScaledInstance(130, 130, Image.SCALE_SMOOTH));
        ImageIcon ii4 = new ImageIcon(im4.getScaledInstance(130, 130, Image.SCALE_SMOOTH));
        ImageIcon ii5 = new ImageIcon(im5.getScaledInstance(130, 130, Image.SCALE_SMOOTH));

//        lbl1.setIcon(ii1);
//        lbl2.setIcon(ii2);
        final List<ImageIcon> imagenes = new ArrayList<>();
        imagenes.add(ii1);
        imagenes.add(ii2);
        imagenes.add(ii3);
        imagenes.add(ii4);
        imagenes.add(ii5);
        
        int pauseMover = 3;// el pause para mover la x de la foto
        int pauseEntreFotos = 1000; // pause entre cada fotos
        
        HiloCoverArt hca = new HiloCoverArt(lbl1, lbl2, imagenes, pauseMover,pauseEntreFotos);
        hca.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
